import type { AvatarConfig } from "./types";

export const skinToneOptions = [
  "#f5d0b5",
  "#e8b38f",
  "#c98d6f",
  "#b56f4d",
  "#8d4d36",
  "#f0e1d6",
  "#ffd166",
  "#ff9f1c",
  "#ff6b6b",
  "#c77dff",
  "#4cc9f0",
  "#80ed99",
  "#bde0fe",
  "#f72585",
];
export const hairColorOptions = [
  "#2b1b12",
  "#473126",
  "#6b4b3a",
  "#94684d",
  "#d7b28f",
  "#7b3f00",
  "#1f2937",
  "#ffffff",
  "#0f766e",
  "#14b8a6",
  "#38bdf8",
  "#60a5fa",
  "#818cf8",
  "#a78bfa",
  "#d8b4fe",
  "#cbd5e1",
];
export const shirtColorOptions = [
  "#ff7f50",
  "#f97316",
  "#facc15",
  "#22c55e",
  "#14b8a6",
  "#0ea5e9",
  "#6366f1",
  "#a855f7",
  "#ec4899",
  "#ef4444",
  "#fb7185",
  "#f43f5e",
  "#eab308",
  "#84cc16",
  "#06b6d4",
  "#8b5cf6",
  "#22d3ee",
  "#f472b6",
  "#111111",
  "#ffffff",
  "#9ca3af",
  "#8b5e34",
];
export const eyeColorOptions = [
  "#1f2937",
  "#111111",
  "#7c3aed",
  "#0f766e",
  "#f43f5e",
  "#06b6d4",
  "#f59e0b",
  "#ffffff",
];
export const mouthColorOptions = [
  "#6b1f2b",
  "#8b3f3f",
  "#b91c1c",
  "#dc2626",
  "#e11d48",
  "#7c3aed",
  "#0f766e",
];

export const defaultAvatarConfig: AvatarConfig = {
  skinColor: skinToneOptions[0],
  hairColor: hairColorOptions[0],
  shirtColor: shirtColorOptions[5],
  eyeColor: eyeColorOptions[0],
  mouthColor: mouthColorOptions[1],
  headShape: "round",
  torsoShape: "box",
  hairStyle: "cap",
  eyes: "dots",
  mouth: "smile",
  accessory: "none",
};

export const avatarShapeOptions = {
  headShape: ["round", "tall", "square"] as const,
  torsoShape: ["box", "oval", "cone", "cylinder", "pyramid", "cube"] as const,
  hairStyle: [
    "bald",
    "buzz",
    "cap",
    "curly",
    "doubleBun",
    "hairDown",
    "ponyTail",
    "pigtails",
    "spiky",
    "sidePart",
  ] as const,
  eyes: [
    "dots",
    "oval",
    "sleepy",
    "wink",
    "sparkle",
    "arc",
    "lines",
    "tenEyes",
  ] as const,
  mouth: ["smile", "flat", "open", "grin", "smirk"] as const,
  accessory: [
    "none",
    "glasses",
    "partyHat",
    "monocle",
    "toteBag",
    "inflatablePoolRing",
    "banana",
    "pizzaHat",
    "moustache",
    "trafficConeHat",
    "cape",
    "wizardHat",
    "baguette",
    "haloHat",
    "cloudHat",
  ] as const,
};

export function toLabel(value: string) {
  return value
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/_/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}
