import type { MemorySite } from "./types";

export const memorySites: MemorySite[] = [
  {
    id: "voice-note-1",
    title: "A voice note",
    description: "A short message from me.",
    type: "voice",
    mediaUrl: "/media/voice-note-1.mp3",
    thumbnailUrl: null,
    noteText: null,
    position: { x: 15.2, y: 0, z: -2.4 },
    rotationY: 0,
    enabled: true,
  },
  {
    id: "photo-1",
    title: "Favorite photo",
    description: "One of my favorite memories.",
    type: "photo",
    mediaUrl: "/media/photo-1.jpg",
    thumbnailUrl: "/media/photo-1-thumb.jpg",
    noteText: "This was such a good day.",
    position: { x: 18, y: 0, z: 1.6 },
    rotationY: 0.5,
    enabled: true,
  },
  {
    id: "video-1",
    title: "Hello Chudrence.",
    description:
      "Welcome to this world. Wait a few seconds for the video to load.",
    type: "video",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/video/upload/q_auto/f_auto/v1781141376/video1_sed71k.mp4",
    thumbnailUrl: null,
    noteText: null,
    position: { x: -12.8, y: 0, z: 0.1 },
    rotationY: 0.1,
    enabled: true,
  },
  {
    id: "video-2",
    title: "Let me try again.",
    description: "This is me trying again I promise",
    type: "video",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/video/upload/q_auto/f_auto/v1781141376/video2_dqmemi.mp4",
    thumbnailUrl: null,
    noteText: null,
    position: { x: -7, y: 0, z: -0.2 },
    rotationY: -0.15,
    enabled: true,
  },
  {
    id: "video-3",
    title: "Ha ha ha.",
    description: "I am dying inside.",
    type: "video",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/video/upload/q_auto/f_auto/v1781141376/video3_uyhcwc.mp4",
    thumbnailUrl: null,
    noteText: null,
    position: { x: -1.2, y: 0, z: 0.5 },
    rotationY: 0.25,
    enabled: true,
  },
  {
    id: "video-4",
    title: "I'll spare you.",
    description:
      "After this video, move around and see what the world has to offer!.",
    type: "video",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/video/upload/q_auto/f_auto/v1781141377/video4_qjyhlp.mp4",
    thumbnailUrl: null,
    noteText: null,
    position: { x: 4.4, y: 0, z: -0.15 },
    rotationY: -0.05,
    enabled: true,
  },
  {
    id: "note-1",
    title: "A note",
    description: "Something I wanted to say.",
    type: "note",
    mediaUrl: null,
    thumbnailUrl: null,
    noteText: "This is a written memory note.",
    position: { x: 13.6, y: 0, z: 4.3 },
    rotationY: 0,
    enabled: true,
  },
];
