import type { MemorySite } from "./types";

export const memorySites: MemorySite[] = [
  {
    id: "photo-1",
    title: "Berlin",
    description: "what a wonderful night",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144457/berlin_hjjbp5.jpg",
    thumbnailUrl: "/media/photo-1-thumb.jpg",
    noteText: "What an eventful night.",
    position: { x: 18, y: 0, z: 1.6 },
    rotationY: 0.5,
    enabled: true,
  },
  {
    id: "photo-2",
    title: "Daytona beach",
    description: "Yeah man, idk what you're doing.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144458/daytona_catveg.jpg",
    thumbnailUrl: null,
    noteText:
      "you weren't even high in this, so i don't know why you wanted to smell my foot. but now i have a great picture of you holding my foot.",
    position: { x: -44, y: 0, z: 14.2 },
    rotationY: -0.35,
    enabled: true,
  },
  {
    id: "photo-3",
    title: "Dumplings!",
    description: "Yummy yummy.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144501/dumpling_j1ezwe.jpg",
    thumbnailUrl: null,
    noteText:
      "making dumplings with everyone was really fun and we should do it one more time in senior year",
    position: { x: -39.5, y: 0, z: -11.8 },
    rotationY: 0.2,
    enabled: true,
  },
  {
    id: "photo-4",
    title: "Banh mi",
    description: "The earliest photo I could find of us",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144502/first_ezvpg6.jpg",
    thumbnailUrl: null,
    noteText:
      "I still remember this night, when we walked to the banh mi place that is closed now across the ice with lana.",
    position: { x: -35.1, y: 0, z: 18.5 },
    rotationY: -0.55,
    enabled: true,
  },
  {
    id: "photo-5",
    title: "Football game",
    description: "Go dores!.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144503/football_e0bajm.jpg",
    thumbnailUrl: null,
    noteText:
      "you mentioned you were excited to go to more games, so next semester we will! and hopefully we will have a good team so we can be happy when we win.",
    position: { x: -31.4, y: 0, z: -17.6 },
    rotationY: 0.4,
    enabled: true,
  },
  {
    id: "photo-6",
    title: "Mallorca",
    description: "French people, huh.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144505/frenchppl_xtv8ht.jpg",
    thumbnailUrl: null,
    noteText:
      "was this a gay date? no, it was a friend date. no homo. ahh, the last trip we had together abroad before it ended. i reminisce so much now.",
    position: { x: -27.2, y: 0, z: 9.7 },
    rotationY: -0.15,
    enabled: true,
  },
  {
    id: "photo-7",
    title: "Graduation",
    description: "Featuring officer jack!.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144506/graduation_tfy2gg.jpg",
    thumbnailUrl: null,
    noteText:
      "a fun and emotional time to see seniors graduate. i can't believe that will be us next year.",
    position: { x: -22.1, y: 0, z: -1.3 },
    rotationY: 0.55,
    enabled: true,
  },
  {
    id: "photo-8",
    title: "Half marathon",
    description: "Will we do this again?",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144508/half_ayvaus.jpg",
    thumbnailUrl: null,
    noteText: "you almost shit yourself, and i left a stain.",
    position: { x: -17.6, y: 0, z: 20.4 },
    rotationY: -0.25,
    enabled: true,
  },
  {
    id: "photo-9",
    title: "Halloween",
    description:
      "Dude couldn't get in and just jizzed on the glass instead with a soap dispenser.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144509/halloween_nh5m4w.jpg",
    thumbnailUrl: null,
    noteText:
      "excited for the next halloween! the haunted house was fun, and we can actually go to broadway now.",
    position: { x: -11.8, y: 0, z: -14.9 },
    rotationY: 0.15,
    enabled: true,
  },
  {
    id: "photo-10",
    title: "Hike!",
    description: "Good memories with good people",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144510/hike_msfupm.jpg",
    thumbnailUrl: null,
    noteText: "more hikes! in the states! and in china! and wherever we go!",
    position: { x: -6.2, y: 0, z: 12.6 },
    rotationY: -0.45,
    enabled: true,
  },
  {
    id: "photo-11",
    title: "idk what this is",
    description: "but it's a cool photo",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144672/idk_hga5xo.jpg",
    thumbnailUrl: null,
    noteText: null,
    position: { x: -1.5, y: 0, z: -19.8 },
    rotationY: 0.3,
    enabled: true,
  },
  {
    id: "photo-12",
    title: "Kisser",
    description: "Ah yes. another gay date.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144673/kisser_bbls7y.jpg",
    thumbnailUrl: null,
    noteText: "i love gay dates. kisser was great. we should do more of these.",
    position: { x: 3.2, y: 0, z: 22.1 },
    rotationY: -0.2,
    enabled: true,
  },
  {
    id: "photo-13",
    title: "Lana's birthday",
    description: "very cool photo.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144675/lanabday_ktvjrh.jpg",
    thumbnailUrl: null,
    noteText: null,
    position: { x: 7.8, y: 0, z: -10.7 },
    rotationY: 0.42,
    enabled: true,
  },
  {
    id: "photo-14",
    title: "Oh boy",
    description: "lights on the lawn. what a night.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144676/lotl_tz06qq.jpg",
    thumbnailUrl: null,
    noteText: "this was... our.... our first... kiss! uwu!",
    position: { x: 12.5, y: 0, z: 15.6 },
    rotationY: -0.38,
    enabled: true,
  },
  {
    id: "photo-15",
    title: "Mitski",
    description: "cool concert.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144677/mitski_muqx4w.jpg",
    thumbnailUrl: null,
    noteText:
      "gay date again. we went to see mitski together and it was really fun! we should go to more concerts together. <- that was ai generated lmfao",
    position: { x: 17.1, y: 0, z: -22.4 },
    rotationY: 0.12,
    enabled: true,
  },
  {
    id: "photo-16",
    title: "Nandos",
    description: "Sigh. another gay date.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144678/nandos_rea3nm.jpg",
    thumbnailUrl: null,
    noteText: "this time in your hometown! crazy that i'm now in DC",
    position: { x: 22.9, y: 0, z: 6.8 },
    rotationY: -0.5,
    enabled: true,
  },
  {
    id: "photo-17",
    title: "Oh no",
    description: "No comment on this night.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144680/nowords_e9zarm.jpg",
    thumbnailUrl: null,
    noteText:
      "rip almost 400 euro. but we bonded with jennifer. she's one of my favorite autists",
    position: { x: 27.4, y: 0, z: -15.2 },
    rotationY: 0.28,
    enabled: true,
  },
  {
    id: "photo-18",
    title: "Photo site 18",
    description: "Add your Cloudinary link here.",
    type: "photo",
    mediaUrl: null,
    thumbnailUrl: null,
    noteText: null,
    position: { x: 31.9, y: 0, z: 19.9 },
    rotationY: -0.18,
    enabled: true,
  },
  {
    id: "photo-19",
    title: "Obliteration",
    description: "the title speaks for itself.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144681/obliteration_mgvhg4.jpg",
    thumbnailUrl: null,
    noteText: null,
    position: { x: 36.8, y: 0, z: -7.4 },
    rotationY: 0.47,
    enabled: true,
  },
  {
    id: "photo-20",
    title: "Pickle",
    description: "WE ARE THETA TAU CHAMPIONS.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144682/pickle_nm8qfv.jpg",
    thumbnailUrl: null,
    noteText: "and intramural champs",
    position: { x: 41.6, y: 0, z: 10.8 },
    rotationY: -0.32,
    enabled: true,
  },
  {
    id: "photo-21",
    title: "Karaoke",
    description: "maybe not the karaoke you were thinking of.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144683/pink_cdbhux.jpg",
    thumbnailUrl: null,
    noteText: "good times huh.",
    position: { x: 46.2, y: 0, z: -20.6 },
    rotationY: 0.16,
    enabled: true,
  },
  {
    id: "photo-22",
    title: "roma",
    description: "chudrence falls prey to food poisoning and constipation.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144684/rome_apdvfb.jpg",
    thumbnailUrl: null,
    noteText: "poor chudrence. never coming back to rome again huh.",
    position: { x: 50.9, y: 0, z: 24.3 },
    rotationY: -0.42,
    enabled: true,
  },
  {
    id: "photo-23",
    title: "Ryanair",
    description:
      "gotta love ryanair. i still haven't gotten my compensation yet, these spanish fuckers.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144686/ryanair_idtstq.jpg",
    thumbnailUrl: null,
    noteText:
      "despite the overbooking, i really enjoyed the hotel stay. i like staying in nice hotels.",
    position: { x: -48.1, y: 0, z: 28.4 },
    rotationY: 0.34,
    enabled: true,
  },
  {
    id: "photo-24",
    title: "San diego",
    description: "Cool photos and cool times.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144687/sd_nomzj3.jpg",
    thumbnailUrl: null,
    noteText: null,
    position: { x: -24.8, y: 0, z: 31.7 },
    rotationY: -0.27,
    enabled: true,
  },
  {
    id: "photo-25",
    title: "Shabu shabu",
    description: "You and your octopodes.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144688/shabu_vwyu3y.jpg",
    thumbnailUrl: null,
    noteText: null,
    position: { x: -3.4, y: 0, z: 29.1 },
    rotationY: 0.21,
    enabled: true,
  },
  {
    id: "photo-26",
    title: "Skiing",
    description: "Yahoo!",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144689/skiing1_tpbmen.jpg",
    thumbnailUrl: null,
    noteText: null,
    position: { x: 19.5, y: 0, z: 27.8 },
    rotationY: -0.36,
    enabled: true,
  },
  {
    id: "photo-27",
    title: "Soran",
    description: "Plus the asians of theta tau.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144691/soran_u30azw.jpg",
    thumbnailUrl: null,
    noteText: "some of the best nights",
    position: { x: 38.4, y: 0, z: 30.5 },
    rotationY: 0.5,
    enabled: true,
  },
  {
    id: "photo-28",
    title: "Sundays at 8",
    description: "the humble beginning.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144692/sundays_x7dabc.jpg",
    thumbnailUrl: null,
    noteText:
      "so much more to come. i will be practising this summer i promise.",
    position: { x: 56.7, y: 0, z: -26.2 },
    rotationY: -0.44,
    enabled: true,
  },
  {
    id: "photo-29",
    title: "Bids",
    description: "Such a beautiful night with the snow.",
    type: "photo",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/image/upload/q_auto/f_auto/v1781144693/thetatau_gag5ti.jpg",
    thumbnailUrl: null,
    noteText:
      "sometimes i wonder how life would have turned out if we both didn't get into theta tau. even if we don't care much about the org now. i'm grateful we got to pledge together.",
    position: { x: 61.3, y: 0, z: -13.1 },
    rotationY: 0.24,
    enabled: true,
  },
  {
    id: "video-1",
    title: "Hello Chudrence.",
    description:
      "Welcome to this world. Wait a few seconds for the video to load.",
    type: "video",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/video/upload/q_auto/f_auto/v1781141376/video1_sed71k.mp4",
    thumbnailUrl: null,
    noteText: null,
    position: { x: -31.2, y: 0, z: -0.55 },
    rotationY: 0.1,
    enabled: true,
  },
  {
    id: "video-2",
    title: "Let me try again.",
    description: "This is me trying again I promise",
    type: "video",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/video/upload/q_auto/f_auto/v1781141376/video2_dqmemi.mp4",
    thumbnailUrl: null,
    noteText: null,
    position: { x: -18.1, y: 0, z: 2.45 },
    rotationY: -0.15,
    enabled: true,
  },
  {
    id: "video-3",
    title: "Ha ha ha.",
    description: "I am dying inside.",
    type: "video",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/video/upload/q_auto/f_auto/v1781141376/video3_uyhcwc.mp4",
    thumbnailUrl: null,
    noteText: null,
    position: { x: -5.4, y: 0, z: -1.4 },
    rotationY: 0.25,
    enabled: true,
  },
  {
    id: "video-4",
    title: "I'll spare you.",
    description:
      "After this video, move around and see what the world has to offer!.",
    type: "video",
    mediaUrl:
      "https://res.cloudinary.com/djial5sti/video/upload/q_auto/f_auto/v1781141377/video4_qjyhlp.mp4",
    thumbnailUrl: null,
    noteText: null,
    position: { x: 8.8, y: 0, z: 0.45 },
    rotationY: -0.05,
    enabled: true,
  },
];
