import type { MemorySite } from "./types";

export const memorySites: MemorySite[] = [
  {
    id: "voice-note-1",
    title: "A voice note",
    description: "A short message from me.",
    type: "voice",
    mediaUrl: "/media/voice-note-1.mp3",
    thumbnailUrl: null,
    noteText: null,
    position: { x: -7, y: 0, z: 4 },
    rotationY: 0,
    enabled: true,
  },
  {
    id: "photo-1",
    title: "Favorite photo",
    description: "One of my favorite memories.",
    type: "photo",
    mediaUrl: "/media/photo-1.jpg",
    thumbnailUrl: "/media/photo-1-thumb.jpg",
    noteText: "This was such a good day.",
    position: { x: 6, y: 0, z: -5 },
    rotationY: 0.5,
    enabled: true,
  },
  {
    id: "video-1",
    title: "Video message",
    description: "A video I recorded.",
    type: "video",
    mediaUrl: "/media/video-message-1.mp4",
    thumbnailUrl: "/media/video-thumb-1.jpg",
    noteText: null,
    position: { x: 8, y: 0, z: 6 },
    rotationY: -0.3,
    enabled: true,
  },
  {
    id: "note-1",
    title: "A note",
    description: "Something I wanted to say.",
    type: "note",
    mediaUrl: null,
    thumbnailUrl: null,
    noteText: "This is a written memory note.",
    position: { x: -5, y: 0, z: -8 },
    rotationY: 0,
    enabled: true,
  },
];
